### ISSUE TITLE
support chrome as well

### ISSUE THREAD

**Issue by fawaf** [Aaron-P/SmartAmazonSmile#1]

**Comment by Aaron-P** [comment]
Chrome [doesn't support asynchronous blocking responses](https://bugs.chromium.org/p/chromium/issues/detail?id=625860) in webRequest.onBeforeRequest listeners.  Since the calls to do things like getting cookies are asynchronous, even in chrome's annoying callback based methods, I'm really not sure how I could make this work in chrome.  If anyone has a working recommendation on how to do this, or if chrome fixes their API, I'll work on it.
